```{r, include = FALSE}
source(here::here("setup.R"))
for (file in list.files(here::here("R"), full.names = TRUE)) source(file)
sample_labels <- readRDS(file.path(output_dir, "sample_labels.rds"))
```

# Putting it all together

We need to process all of them and combine the resulting data frames in one big data frame.

```{r}
all_filenames <- list.files(train_dir, pattern = "^(acc|gyro)")
cat("Number of files:", length(all_filenames))
```

```{r}
n_samples_per_epoch <- 128
sample_rate <- 50

df <- map_dfr(
    all_filenames,
    parse_and_features,
    dir = train_dir,
    sample_labels = sample_labels,
    n_samples_per_epoch = n_samples_per_epoch,
    sample_rate = sample_rate,
    .progress = "Parsing all files, gathering features"
)
head(df)
summary(df)
```

## Cleaning

We really should check for NA's

```{r}
sum(is.na(df))
```

Removing columns unneccessary for fitting.

```{r}
df <- df |> select(-epoch, -sampleid, -n_samples)
```

```{r}
# df_numeric <- df |> select_if(is.numeric)
# linear_combos <- caret::findLinearCombos(df_numeric)
# redundant <- names(df_numeric)[linear_combos$remove]
# redundant
```

## Visualizing features

```{r}
df |>
    filter(activity_confidence > 0) |>
    pivot_longer(cols = -c(activity_confidence, aggr_activity), names_to = "feature", values_to = "value") |>
    ggplot(aes(value, color = aggr_activity)) +
    geom_density() +
    facet_wrap(~feature, scales = "free")
```

Now the data are turned into a tidy format with features that can be used in any of the algorithms.

```{r, include = FALSE}
saveRDS(df, file.path(output_dir, "df.rds"))
```
